### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by oversecio** [comment]
This is amazing! Thank you so much!

**Comment by oversecio** [comment]
Will release an update containing your work sometime this weekend!

**Comment by linsui** [comment]
I have a question. What's the difference between keyphrase and passphrase? :joy:

**Comment by mgeier63** [comment]
passphrase is used to unlock (another) key.
keyphrase is used as a key itself.

Not sure if it makes sense to use two different words, feel free to use a common translation if that makes more sense...

**Pull request merged**
